name: iQA
description: "iQA."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fluttertoast: ^8.2.8
  dio: ^5.7.0
  shimmer: ^3.0.0
  intl: any
  provider: ^6.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.7
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.0
  logger: ^2.4.0
  go_router: ^14.2.7


  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"


flutter_native_splash:
  image: "assets/images/splash_icon.png"
  color: "#FFFFFF"
  android_12:
    image: "assets/images/splash_icon.png"
    color: "#FFFFFF"
  android: true
  ios: true
  web: false

  assets:
    - assets/images/
    - assets/svgImages/
    - assets/
